import { EndpointSpecType, JSONValue } from '../type.ts';
import { renderParamsTypeZod } from './renderParams.ts';
import { renderResponse } from './renderResponse.ts';
import { renderType } from './renderType.ts';
import { toBigCamelCase, wordFirstLetterToLower } from './toBigCamelCase.ts';
import { renderResponseGeneric } from './renderResponseGeneric.ts';
import { generateUrlAll } from './generateUrlAll.ts';
import { renderImports } from './renderModels.ts';

const getBody = (spec: EndpointSpecType): string => {
    for (const param of spec.parameters) {
        if (param.in === 'body') {
            const name = param.name;
            return `params.${name}`;
        }
    }

    return 'undefined';
};

const generateHeadersType = (parameters: EndpointSpecType['parameters']): string => {
    const headers: string[] = [];

    const typeParam = 'type ExtraHeadersType = z.TypeOf<typeof ExtraHeadersZod>;';

    for (const param of parameters) {
        if (param.in === 'header') {
            const name = param.name;
            const paramType = renderType(4, param.schema);
            if (name.includes('-')) {
                headers.push(`    '${name}': ${paramType},`);
            } else {
                headers.push(`    ${name}: ${paramType},`);
            }
        }
    }

    if (headers.length > 0) {
        const headersJoin = headers.join('\n');
        return `const ExtraHeadersZod = z.object({\n${headersJoin}\n});\n${typeParam}\n`;
    }

    return `const ExtraHeadersZod = z.record(z.string(), z.string());\n${typeParam}\n`;
};

const generateHeadersParam = (parameters: EndpointSpecType['parameters']): string => {

    let counter = 0;

    for (const param of parameters) {
        if (param.in === 'header') {
            counter += 1;
        }
    }

    if (counter > 0) {
        return 'extraHeaders: ExtraHeadersType';
    }

    return 'extraHeaders?: ExtraHeadersType';
};

export const renderEndpoint = (openApiSpec: JSONValue, nameInFile: string, method: string, url: string, handler: EndpointSpecType): string => {
    const imports = renderImports(openApiSpec, handler);
    const generateParamsDef = renderParamsTypeZod(handler);
    const generateResponseIoData = renderResponse(handler, url, method);
    const generateMethod = method;
    const generateBody = getBody(handler);
    const extraHeadersType = generateHeadersType(handler.parameters);
    const extra_headers = generateHeadersParam(handler.parameters);

    const nameInFileCamelcaseBig = toBigCamelCase(nameInFile);
    const nameInFileCamelcaseSmall = wordFirstLetterToLower(nameInFileCamelcaseBig);
    const [genericResponseTypes, genericResponseIfs] = renderResponseGeneric(
        nameInFileCamelcaseBig,
        handler
    );
    // const queryStringParams = queryStringParams(handler.parameters);
    const urlCode = generateUrlAll(url, handler);

    const content = `/* eslint-disable */
//The contents of this file have been generated automatically. Do not edit this file.

import { z } from 'zod';
${imports}

${generateParamsDef}

${generateResponseIoData}

${extraHeadersType}

export type ${nameInFileCamelcaseBig}ParamsType = ParamsType;

${genericResponseTypes}

const convertHeaders = (params: Record<string, string | null | undefined>): Record<string, string> => {
    const result: Record<string, string> = {};

    for (const [name, value] of Object.entries(params)) {
        if (value !== null && value !== undefined) {
            result[name] = value;
        }
    }

    return result;
};

export const ${nameInFileCamelcaseSmall}Request = async (
    api_url: string,
    params: ParamsType,
    ${extra_headers}
): Promise<${nameInFileCamelcaseBig}ResponseType> => {
    const ok = ParamsTypeZOD.safeParse(params);
    if (!ok.success) {
        console.error('Input parameters do not match the definition from openapi');
    }

    ${urlCode}

    const headers = convertHeaders({
        'Content-Type': 'application/json; charset=utf-8',
        ...extraHeaders
    });

    let response: Response | null = null;
    try {
        response = await fetch(url, {
            method: '${generateMethod.toUpperCase()}',
            headers,
            body: JSON.stringify(${generateBody}),
            credentials: 'include'
        });
    } catch (error) {
        return {
            status: 0,
            body: \`${generateMethod.toUpperCase()}:\${url} \${error instanceof Error ? error.message : String(error)}\`
        };
    }

    const status = response.status;

    let json = null;

    try {
        const text = await response.text();
        if (text !== '') {
            json = JSON.parse(text);
        }
    } catch (_err) {
        return {
            status: 0,
            body: \`${generateMethod.toUpperCase()}:\${url} -> Http status \${status} - json was expected\`
        };
    }
    ${genericResponseIfs}

    throw new Error(\`${nameInFileCamelcaseSmall}Request - unhandled response \${status}\`);
};
`;

    return content;
};

